@startuml
!define id(x) class x << U,white,Id >>
!define hash(x) class x << H,white,Hash >>
!define int(x) class x << I,white,Int >>
!define list(x) class x << L,white,List >>
!define set(x) class x << S,white,Set >>
!define json(x) class x << J,white,Json >>
!define simple(x) class x << K,white,Simple >>
!define key(x) <u><b>x</b></u>
hide methods
hide stereotypes

skinparam class {

    borderColor Black
    backgroundColor<<Id>> Gold
    backgroundColor<<Hash>> LightSalmon
    backgroundColor<<Int>> Gold
    backgroundColor<<List>> GreenYellow
    backgroundColor<<Set>> Plum
    backgroundColor<<Json>> Pink
    backgroundColor<<Simple>> LightBlue

}

package user {

    id(UserId)

    hash(Device)<<OO>> {
        key(deviceId)
        + userId
        + appVersion
        + locale
        + model
        + cordova
        + platform
        + version
    }

    hash(User) {
        key(userId)
        + name
        + gender
        + facebookId
        + phone
        + phoneVerified
        + lastLoginTime
    }

    simple(FacebookToken) {
        key(token)
        facebookId
    }

    simple(FacebookUser) {
        key(facebookId)
        + userId
    }

    simple(Phone) {
        key(phone)
        + userId
    }

    int(PhoneCooldown) {
        key(phone)
        Exists
    }

    set(UserGroups) {
        key(userId)
        GroupId
    }

}

package group {

    id(GroupId)

    hash(Group) {
        key(groupId)
        + lastEventTime
        + eventCount
    }

    hash(GroupUser) {
        key(groupId+userId)
        + lastReadTime
    }

    list(GroupEvents) {
        key(groupId)
        - id
        - groupId
        - userId
        - type
        - body
        - time
    }

    package GroupUserQuestion #White/Plum {

        set(GroupUserQuestions) {
            key(groupId+userId)
            QuestionIdComposite
        }

        set(GroupUserQuestionsTemp) {
            key(groupId+userId)
            QuestionIdComposite
        }

        set(GroupUserQuestionsYes) {
            key(groupId+userId)
            QuestionIdComposite
        }

    }

    set(GroupUsers) {
        key(groupId)
        UserId
    }

    simple(GroupPair) {
        key(userId+userId)
        GroupId
    }

}

package question {

    id(QuestionIdComposite)

    set(Questions) {
        key("standard")
        QuestionIdComposite
    }

}

package userland <<Cloud>> {

    hash(PhysicalDevice) {
        + phone
        + deviceId
    }

    hash(FacebookAccount) {
        + token
    }

}

package legend <<Rect>> #White/Gainsboro {

    note top of "Id Key"
        Id keys are special,
        they produce auto-
        incrementing ints
    end note

    id("Id Key")

    hash("Hash Key") {
        key(token)
        + prop 1
        + prop 2
        + ...
        + prop n
    }

    int("Int Key") {
        key(token)
        $intval
    }

    list("List Key") {
        key(token)
        $type
    }

    set("Set Key") {
        key(token)
        $type
    }

    json("Json Key") {
        key(token)
        - json field 1
        - json field 2
        - ...
        - json field n
    }

    simple("Simple Key") {
        key(token)
        $type
    }

}

FacebookAccount -* FacebookToken
FacebookToken --* FacebookUser
GroupId -* Group
GroupId --* GroupUserQuestion
GroupId --* GroupEvents
GroupId --* GroupUser
GroupId --* GroupUsers
PhysicalDevice --* Device
PhysicalDevice --* Phone
PhysicalDevice --* PhoneCooldown
UserId --* GroupUserQuestion
UserId --* User
UserId --* GroupPair
UserId --* GroupPair
UserId --* GroupUser
UserId --* UserGroups

@enduml